### ISSUE TITLE
备忘录：官方release commit的SHA

### ISSUE THREAD

**Issue by HaloSense** [VM-Chinese-translate-group/create_astral_translation_zhcn#19]
在这里记录官方库的commit SHA，以备不时之需。

**Comment by HaloSense** [comment]
版本：2.0.2
SHA：`a32f85311b92c1bace748665f6fb782955600146`

**Comment by HaloSense** [comment]
版本：2.0.4
SHA：`881e1aff792f60c888554e1855fb901956b5978b`

**Comment by spaceskynet** [comment]
版本：2.0.4b
SHA：`30e61b803d69c1d38b0f1445f75a6eac9ed9b8e5`

**Comment by HaloSense** [comment]
版本：2.0.4b
SHA：`62b387e4a168fcacca88a09d1bdb345d9922be87`
