### ISSUE TITLE
WIP：Dave's Building Extended 模组翻译

### ISSUE THREAD

**Issue by HaloSense** [VM-Chinese-translate-group/create_astral_translation_zhcn#25]
计划进行翻译之后投递到[自动汉化模组官方库](https://github.com/HaloSense/Minecraft-Mod-Language-Package)，有想参与的在这条issue下留言。

**Comment by Wulian233** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/4383
已经包含，关闭issue
