### ISSUE TITLE
Note: Contents to be made translatable

### ISSUE THREAD

**Issue by HaloSense** [VM-Chinese-translate-group/create_astral_translation_zhcn#27]
- [ ] Quest texts: Titles, subtitles, descriptions, task titles, etc (this includes additional tasks that are added halfway)
- [ ] Block / item tooltips
- [ ] Ponder information and directions
- [ ] Custom machinery block name (probably put a placeholder in the kubejs or whatever startup file)

**Comment by arc25275** [comment]
Ponders: need keys from `kubejs\assets\ponderjs_generated\lang`, and the code used is `Text.translate(key).getString()`
Other KubeJs scripts (tooltips for example) uses keys from `kubejs\lang\` and the code used is `Text.translate(key)`

**Comment by HaloSense** [comment]
> Ponders: need keys from `kubejs\assets\ponderjs_generated\lang`, and the code used is `Text.translate(key).getString()` Other KubeJs scripts (tooltips for example) uses keys from `kubejs\lang\` and the code used is `Text.translate(key)`

Noted, all contributors will be notified to refer to this issue for future works.

**Comment by arc25275** [comment]
For ponderjs, you actually shouldnt need to change any code; just create the lang file according to the en_us.json version. This will all be added when I'm done with the ponder stuff
