### ISSUE TITLE
重要：麻烦各位参与汉化的人员查看这条issue并回复

### ISSUE THREAD

**Issue by HaloSense** [VM-Chinese-translate-group/create_astral_translation_zhcn#6]
请在本条issue下回复附上你的b站id（如有）并提供个人主页的超链接，之后我更新专栏的时候会附上各位的id
如果可以的话请加群：754607929方便交流

**Comment by spaceskynet** [comment]
[B站](https://space.bilibili.com/183453841)同名，最近刚把1.2的[汉化整合](https://www.bilibili.com/read/cv21425183)了，没想到2.0就出来了:P

**Comment by DrGolden2022** [comment]
B站[@金币Golden](https://space.bilibili.com/419105073)
_感觉翻的有点少的说_

**Comment by kressety** [comment]
B站ID：[东上Akaneki](https://space.bilibili.com/2209567)
很荣幸尽到一份绵薄之力。
